on:
  push:
    tags:
      - v**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn
      - run: yarn build

      - run: echo ${{ github.ref }}
      - run: node scripts/version.js ${{ github.ref }}
      - run: npm version

      # - uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
